webtalk_init -webtalk_dir D:/self_learning/RISC-V-RV32I-CPU/risc_v_cpu1/risc_v_cpu1.sim/sim_1/behav/xsim/xsim.dir/CPU_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Mar  5 20:12:19 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "84a7a492-c3c1-40e2-860a-feee84c2ec00" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ebaa427a70ae49daa2bc36429536826e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "129" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "13" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "275 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "35 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "527" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "22" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.37_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "80076_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1723381584 -regid "" -xml D:/self_learning/RISC-V-RV32I-CPU/risc_v_cpu1/risc_v_cpu1.sim/sim_1/behav/xsim/xsim.dir/CPU_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/self_learning/RISC-V-RV32I-CPU/risc_v_cpu1/risc_v_cpu1.sim/sim_1/behav/xsim/xsim.dir/CPU_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/self_learning/RISC-V-RV32I-CPU/risc_v_cpu1/risc_v_cpu1.sim/sim_1/behav/xsim/xsim.dir/CPU_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
