# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/self_learning/RISC-V-RV32I-CPU/1/risc_v_cpu1/risc_v_cpu1.srcs/sources_1/ip/inst_blkmem/inst_blkmem.xci
# IP: The module: 'inst_blkmem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/self_learning/RISC-V-RV32I-CPU/1/risc_v_cpu1/risc_v_cpu1.srcs/sources_1/ip/inst_blkmem/inst_blkmem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_blkmem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/self_learning/RISC-V-RV32I-CPU/1/risc_v_cpu1/risc_v_cpu1.srcs/sources_1/ip/inst_blkmem/inst_blkmem.xci
# IP: The module: 'inst_blkmem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/self_learning/RISC-V-RV32I-CPU/1/risc_v_cpu1/risc_v_cpu1.srcs/sources_1/ip/inst_blkmem/inst_blkmem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_blkmem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
